#!/bin/bash

prog=$(basename $0)
author="techgaun"
desc="Brutally simple password manager for bash"
version="0.0.1"
red='\033[0;31m'
green='\033[0;32m'
nc='\033[0m'

password_file="${HOME}/.saancho.gpg"

error() {
    msg="${1:-$default_err}"
    echo -e "${red}${msg}${nc}"
    exit 1
}

msg() {
    msg="${1:-nothing}"
    echo -e "${green}${msg}${nc}"
}

is_debian() {
    [[ -f "/usr/bin/apt-get" ]]
}

is_rhel() {
    [[ -f "/usr/bin/yum" ]]
}

is_arch() {
    [[ -f "/usr/bin/pacman" ]]
}

cmd=$(command -v gpg2 || command -v gpg)

if [[ "$?" -ne "0" ]]; then
  echo "Could not find gpg binary. Trying to install gpg..."
  if is_debian; then
    sudo apt install -y gnupg2
    if [[ "$?" -ne "0" ]]; then
      sudo apt install -y gnupg
    fi
  elif is_rhel; then
    sudo yum install -y gnupg2
    if [[ "$?" -ne "0" ]]; then
      sudo yum install -y gnupg
    fi
  elif is_arch; then
      sudo pacman -S gnupg
  else
    error "Unknown distribution. Please install gnupg2/gnupg for your distribution and use ${prog}."
  fi
fi

if [[ ! -e "${password_file}" ]]; then
  msg "Saancho store does not exist. Creating..."
  password=""
  while [[ "x" == "x${password}" ]]; do
    read -s -p "Enter the passphrase for your saancho store: " password
    echo ""
  done
  touch $password_file
  echo $password | ${cmd} --passphrase-fd 0 --batch $password_file || rm -f $password_file
fi
